import React, { useState } from "react";
import { Alert, AlertDescription, AlertTitle } from "./ui/alert"; // Adjust path to your shadcn Alert component
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card"; // Adjust path to your shadcn Card component
import { Label } from "./ui/label"; // Adjust path to your shadcn Label component
import { Textarea } from "./ui/textarea"; // Adjust path to your shadcn Textarea component

// Import your icons from lucide-react or similar library
import {
  Calculator,
  CreditCard,
  DollarSign,
  ExternalLink,
  FlaskConical,
  Heart,
  Info,
  Lightbulb,
  PiggyBank,
  RotateCcw,
  Save,
  Scale,
  Settings,
  Shield,
  ShoppingCart,
  Target,
} from "lucide-react";
import { Button } from "./ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./ui/tabs";

// --- Type Definitions (Copy these from your existing codebase if they exist) ---
type FinancialStatus =
  | "On Track"
  | "Needs Attention"
  | "Excellent"
  | "Critical";

interface ModuleInsight {
  id: string;
  title: string;
  icon: React.ElementType; // Assumes `icon` is a React component like `DollarSign`
  score: number;
  status: FinancialStatus;
  comprehensiveAnalysis: string; // The *output* generated by AI, not the prompt
  externalContext: string; // The *output*
  strategicRecommendations: { type: string; text: string }[]; // The *output*
  behavioralInsights: string; // The *output*
  comparisonBenchmarking: string; // The *output*
  metrics: { label: string; value: string; change: number; period: string }[];
  linkText: string;
  linkModule: string;
}

// --- NEW Type Definition for Prompt Templates ---
interface ModulePromptTemplates {
  [moduleId: string]: {
    comprehensiveAnalysisPrompt: string;
    externalContextPrompt: string;
    strategicRecommendationsPrompt: string;
    behavioralInsightsPrompt: string;
    comparisonBenchmarkingPrompt: string;
  };
}

// --- Your Provided moduleInsights Data (Copy-paste directly) ---
const moduleInsights: ModuleInsight[] = [
  {
    id: "cash-flow",
    title: "Income & Cash Flow Dynamics",
    icon: DollarSign,
    score: 8.1,
    status: "On Track" as FinancialStatus,
    comprehensiveAnalysis: `The client's net cash flow for January was RM 2,847, representing an 8% decrease from December, primarily influenced by anticipated seasonal spending and one-off Chinese New Year expenses. Despite this monthly fluctuation, the underlying income streams from primary employment and a side hustle demonstrate consistent stability. The recent salary increase (effective January) has positively impacted the annual income baseline. System projects a return to positive cash flow growth in February, barring unforeseen expenses.`,
    externalContext: `Malaysia's labour market exhibited resilience in Q4 2023 (unemployment at 3.3%), ensuring primary income stability. However, the services sector, where the client's side hustle operates, shows moderate wage growth. This market context underscores the importance of a robust emergency fund and diversified income strategy.`,
    strategicRecommendations: [
      {
        type: "Immediate Action",
        text: "Propose setting up an automated transfer of RM 400 to the high-yield savings account immediately post-payday to ensure consistent cash flow optimization.",
      },
      {
        type: "Mid-Term Strategy",
        text: "Review and categorize the one-off CNY expenses to differentiate between necessary and discretionary seasonal spending for future budget planning.",
      },
      {
        type: "Long-Term Consideration",
        text: "Discuss exploring additional passive income streams aligned with client's skills to further enhance income diversification and hedge against primary income volatility.",
      },
    ],
    behavioralInsights:
      "Client tends to spend more aggressively on discretionary items when cash flow is high, suggesting a 'treat yourself' pattern post-income events.",
    comparisonBenchmarking:
      "Client's income diversification (3 sources) is above average for their age group, contributing to a lower overall income volatility index compared to peers.",
    metrics: [
      { label: "Net Cash Flow", value: "RM 2,847", change: -8, period: "MoM" },
      {
        label: "Income Stability",
        value: "Excellent",
        change: 0,
        period: "3 diverse streams",
      },
      {
        label: "Emergency Fund",
        value: "4.2 months",
        change: 5,
        period: "of expenses",
      },
    ],
    linkText: "Analyze Cash Flow Projections",
    linkModule: "home",
  },
  {
    id: "spending",
    title: "Spending Patterns & Efficiency Analysis",
    icon: ShoppingCart,
    score: 6.8,
    status: "Needs Attention" as FinancialStatus,
    comprehensiveAnalysis: `Client's total spending of RM 4,235 represented 68% of income this month, a 12% increase from December. The top expenditure categories were Food & Dining (RM 856), Transportation (RM 542), and Shopping (RM 426). Anomaly detection flagged a significant acceleration in dining out expenses mid-month, particularly on weekends, leading to a RM 380 budget overrun. This indicates a 'lifestyle creep' where comfort spending is increasing disproportionately to income growth.`,
    externalContext: `Rising inflation, particularly a 3% increase in RON95 petrol and 5% rise in restaurant costs due to minimum wage adjustments, contributed to higher transport and dining expenses for Malaysian households. While some increases are external, the client's spending velocity in discretionary categories is above market trends.`,
    strategicRecommendations: [
      {
        type: "Immediate Action",
        text: "Collaborate with the client to implement a strict weekly spending limit for Food & Dining (e.g., RM 200/week), utilizing transaction alerts.",
      },
      {
        type: "Mid-Term Strategy",
        text: "Encourage meal planning and preparing more meals at home to reduce dining out frequency by 2-3 times per week, aiming for a RM 250 monthly saving.",
      },
      {
        type: "Long-Term Consideration",
        text: "Conduct a comprehensive review of all recurring subscription services; the system detected RM 127 in potential non-essential monthly charges.",
      },
    ],
    behavioralInsights:
      "The system identified a correlation between increased discretionary spending and periods of high work-related stress, suggesting spending as a coping mechanism. This is a key discussion point.",
    comparisonBenchmarking:
      "Client's discretionary spending as a percentage of income is 10% higher than similar income-level peers who are actively saving for a house down payment.",
    metrics: [
      { label: "Total Spending", value: "RM 4,235", change: 12, period: "MoM" },
      {
        label: "Budget Adherence",
        value: "78%",
        change: -15,
        period: "of categories on track",
      },
      {
        label: "Lifestyle Creep",
        value: "RM 450/month",
        change: 0,
        period: "over 6 months",
      },
    ],
    linkText: "Deep Dive into Spending Breakdown",
    linkModule: "spending",
  },
  {
    id: "debt",
    title: "Debt Management & Credit Health Optimization",
    icon: CreditCard,
    score: 8.7,
    status: "Excellent" as FinancialStatus,
    comprehensiveAnalysis: `Client demonstrated exceptional progress in debt reduction, successfully reducing total debt by RM 2,450 this month, primarily through accelerated payments on the CIMB credit card. This proactive approach has significantly improved the Debt-to-Income (DTI) ratio to a healthy 28%, well within the recommended 30% threshold. However, the credit card utilization (CCU) remains high at 65%, which, despite consistent payments, can negatively impact the credit score.`,
    externalContext: `Bank Negara's recent 25 basis point OPR increase to 3.00% will impact the client's variable-rate housing loan starting next month, potentially increasing monthly payments. This macroeconomic shift necessitates a review of the current debt strategy to mitigate increased interest costs.`,
    strategicRecommendations: [
      {
        type: "Immediate Action",
        text: "Formulate a concrete plan to reduce credit card utilization below 30% within 2 months by allocating an additional RM 1,200 towards the balance, potentially using surplus from holiday fund completion.",
      },
      {
        type: "Mid-Term Strategy",
        text: "Conduct a detailed analysis on refinancing options for the variable-rate housing loan if prevailing market rates offer a reduction of 0.5% or more, exploring fixed-rate alternatives.",
      },
      {
        type: "Long-Term Consideration",
        text: "Continue the 'debt avalanche' strategy, directing any freed-up cash flow (e.g., from PTPTN payoff) towards the Maybank personal loan, which carries the highest fixed interest rate.",
      },
    ],
    behavioralInsights:
      "Client is highly motivated by tangible debt reduction progress, which can be leveraged for sustained discipline. The challenge lies in consistent credit card management to avoid high utilization.",
    comparisonBenchmarking:
      "Client's debt reduction rate is 20% faster than the average for individuals with similar DTI ratios, showcasing strong financial discipline.",
    metrics: [
      {
        label: "Total Debt",
        value: "RM 187,450",
        change: -1.3,
        period: "MoM reduction",
      },
      {
        label: "Debt-to-Income",
        value: "28%",
        change: -3,
        period: "optimal ratio",
      },
      {
        label: "CC Utilization",
        value: "65%",
        change: 0,
        period: "needs reduction",
      },
    ],
    linkText: "Strategize Debt Repayment",
    linkModule: "debts",
  },
  {
    id: "investments",
    title: "Savings & Investment Portfolio Performance",
    icon: PiggyBank,
    score: 7.9,
    status: "Excellent" as FinancialStatus,
    comprehensiveAnalysis: `The client's savings rate reached an commendable 22% this month, positioning them ahead of schedule for the emergency fund goal. The investment portfolio demonstrated a robust 3.2% gain this month, outperforming the FBM KLCI by 1.8%. However, analysis identifies a notable 45% concentration in technology stocks, which, while beneficial during growth cycles, exposes the portfolio to undue sectoral risk during downturns. Rebalancing is crucial for long-term stability.`,
    externalContext: `Global market volatility, driven by US inflation concerns and China's economic reopening, created mixed signals for ASEAN markets. Malaysian REITs showed resilience, while technology stocks experienced higher volatility. This external environment reinforces the need for strategic diversification away from concentrated positions.`,
    strategicRecommendations: [
      {
        type: "Immediate Action",
        text: "Propose a portfolio rebalancing strategy to reduce technology sector concentration to below 35%, reallocating funds into more diversified sectors or asset classes (e.g., healthcare, consumer staples).",
      },
      {
        type: "Mid-Term Strategy",
        text: "Recommend increasing monthly contributions to the Versa robo-advisor by RM 300 to leverage its automated diversification and exposure to a broader market.",
      },
      {
        type: "Long-Term Consideration",
        text: "Conduct an in-depth review of ASB investment potential; the client's current contributions appear underutilized, missing out on consistent, low-risk returns.",
      },
    ],
    behavioralInsights:
      "Client shows a natural inclination towards high-growth sectors, driven by perceived higher returns. Education on risk-adjusted returns and diversification benefits will be key.",
    comparisonBenchmarking:
      "Client's portfolio return (3.2% MoM) is in the top quartile compared to balanced portfolios within their risk profile. However, tech concentration is 15% higher than recommended benchmarks.",
    metrics: [
      { label: "Savings Rate", value: "22%", change: 12, period: "of income" },
      {
        label: "Portfolio Return",
        value: "+3.2%",
        change: 0,
        period: "this month",
      },
      {
        label: "Tech Concentration",
        value: "45%",
        change: 0,
        period: "needs reduction",
      },
    ],
    linkText: "Optimize Investment Portfolio",
    linkModule: "investments",
  },
  {
    id: "retirement",
    title: "Retirement Planning & Readiness Assessment",
    icon: Shield,
    score: 7.4,
    status: "On Track" as FinancialStatus,
    comprehensiveAnalysis: `Based on current contribution levels and projected income, the client is 74% on track to achieve their desired retirement lifestyle at age 60. The EPF Account 1 balance saw a healthy growth of RM 892 this month (including employer contributions and dividends). The client's self-reported retirement confidence level is 72%, which is commendable, but slight adjustments can significantly enhance long-term security.`,
    externalContext: `EPF's 2023 dividend of 5.5% for conventional savings exceeded expectations, positively impacting retirement balances. The government's continued offering of additional PRS tax relief up to RM 3,000 presents a significant, underutilized opportunity for tax optimization and accelerated retirement savings.`,
    strategicRecommendations: [
      {
        type: "Immediate Action",
        text: "Advise increasing voluntary EPF contribution by RM 200/month to fully leverage tax benefits and compound higher returns, especially if it falls within the current tax relief limits.",
      },
      {
        type: "Mid-Term Strategy",
        text: "Recommend opening and contributing to a Private Retirement Scheme (PRS) account to utilize the full RM 3,000 annual tax relief, diversifying retirement assets beyond EPF.",
      },
      {
        type: "Long-Term Consideration",
        text: "Simulate 'what-if' scenarios with the client: illustrate the profound impact of working until 62 instead of 60 on projected retirement income and financial security, providing data-driven rationale.",
      },
    ],
    behavioralInsights:
      "Client understands the importance of retirement planning but may underestimate the power of early, consistent, and optimized contributions. Visualizing long-term compound growth is effective.",
    comparisonBenchmarking:
      "Client's EPF balance growth rate is consistent with average, but overall retirement readiness score (74%) is 5% below individuals actively utilizing all available tax-advantaged retirement vehicles.",
    metrics: [
      {
        label: "Readiness Score",
        value: "74%",
        change: 2,
        period: "confidence level",
      },
      {
        label: "EPF Balance",
        value: "RM 125,650",
        change: 0.7,
        period: "monthly growth",
      },
      {
        label: "Years to Target",
        value: "28 years",
        change: 0,
        period: "until retirement",
      },
    ],
    linkText: "Refine Retirement Strategy",
    linkModule: "retirement",
  },
  {
    id: "tax",
    title: "Tax Efficiency & Optimization Opportunities",
    icon: Calculator,
    score: 6.5,
    status: "Needs Attention" as FinancialStatus,
    comprehensiveAnalysis: `For the tax year 2023, the client utilized RM 4,200 in tax reliefs, primarily from lifestyle (RM 2,500, max RM 2,500) and medical expenses (RM 1,200). However, the system has identified RM 800 in potential unused lifestyle relief and a complete underutilization of the PRS contribution relief (up to RM 3,000). There's a significant opportunity to reduce tax liability for the upcoming filing.`,
    externalContext: `Budget 2024 introduced enhanced tax relief for electric vehicle purchases and increased medical expense limits to RM 10,000, creating new opportunities. The e-filing deadline of April 30, 2024, is approaching, with penalties for late submission. Staying updated on these changes is crucial for maximizing client benefits.`,
    strategicRecommendations: [
      {
        type: "Immediate Action",
        text: "Alert client to categorize RM 450 in unclassified medical transactions detected in their spending to claim additional medical relief, potentially reducing tax payable.",
      },
      {
        type: "Mid-Term Strategy",
        text: "Discuss strategic purchases (e.g., books, sports equipment) to utilize the remaining RM 800 lifestyle relief before the tax year end.",
      },
      {
        type: "Long-Term Consideration",
        text: "Develop a proactive strategy for PRS contributions, aiming to fully utilize the RM 3,000 deduction annually, potentially through automated monthly transfers.",
      },
    ],
    behavioralInsights:
      "Client demonstrates good record-keeping but may not be fully aware of the breadth of available tax reliefs or the strategic timing of certain expenditures.",
    comparisonBenchmarking:
      "Client's tax relief utilization is 15% below the average for similar income brackets due to underutilization of investment-related and lifestyle reliefs.",
    metrics: [
      {
        label: "Reliefs Used",
        value: "RM 4,200",
        change: 0,
        period: "of available",
      },
      {
        label: "Est. Refund/Payable",
        value: "RM 1,247 Refund",
        change: 15,
        period: "based on current",
      },
      {
        label: "Filing Progress",
        value: "65%",
        change: 0,
        period: "documents ready",
      },
    ],
    linkText: "Optimize Tax Strategy",
    linkModule: "taxes",
  },
  {
    id: "insurance",
    title: "Insurance & Risk Protection Audit",
    icon: Heart,
    score: 8.3,
    status: "On Track" as FinancialStatus,
    comprehensiveAnalysis: `The client's insurance portfolio is generally comprehensive, covering 4 out of 5 key protection areas (Life, Medical, Accident, Property). Deep analysis confirms adequate life coverage at 8x annual income, which aligns with industry best practices. However, a critical illness coverage gap has been identified, particularly pertinent given the client's family history of cardiovascular issues.`,
    externalContext: `Rising healthcare costs in Malaysia (averaging 10% annually) and increased medical inflation post-pandemic make regular review of medical insurance limits critical. The government's MySalam program provides additional coverage, but the client's income bracket may not qualify for maximum benefits, emphasizing private policy importance.`,
    strategicRecommendations: [
      {
        type: "Immediate Action",
        text: "Propose a critical illness rider addition to the existing life policy, or a standalone critical illness plan, providing an additional RM 100,000 coverage.",
      },
      {
        type: "Mid-Term Strategy",
        text: "Review the medical insurance annual limit (currently RM 150,000) against current healthcare cost trends and family needs, considering an increase to RM 200,000.",
      },
      {
        type: "Long-Term Consideration",
        text: "Evaluate home insurance coverage following recent property valuation increase to ensure adequate rebuilding cost coverage and protection against natural disasters.",
      },
    ],
    behavioralInsights:
      "Client is receptive to risk mitigation but needs data-driven insights to justify additional premium outlays. Highlighting family history impact is effective.",
    comparisonBenchmarking:
      "Client's overall protection score is 10% higher than peers who only maintain basic compulsory insurance, but trails those with comprehensive critical illness coverage.",
    metrics: [
      {
        label: "Protection Score",
        value: "83%",
        change: 5,
        period: "coverage adequacy",
      },
      {
        label: "Active Policies",
        value: "4 policies",
        change: 0,
        period: "across key areas",
      },
      {
        label: "Premium Efficiency",
        value: "Good",
        change: 0,
        period: "cost vs coverage",
      },
    ],
    linkText: "Audit Coverage & Premiums",
    linkModule: "insurance",
  },
];
// --- End of Provided moduleInsights Data ---

// --- Initial Prompt Templates (example structure with placeholders) ---
// These are the *default* prompts that can be configured.
const initialModulePromptTemplates: ModulePromptTemplates = {
  "cash-flow": {
    comprehensiveAnalysisPrompt: `Generate a comprehensive analysis of the client's cash flow for the past month (e.g., January). Include:
- Net cash flow: {{client.netCashFlow}} and its MoM change: {{client.netCashFlowChange}}%.
- Primary influences for changes: {{client.primaryInfluences}}.
- Income stability from diverse streams: {{client.incomeStreams}} (e.g., primary employment, side hustle).
- Impact of recent salary increase (effective: {{client.salaryIncreaseMonth}}).
- Projected cash flow growth for February, noting conditions for positive growth.
`,
    externalContextPrompt: `Provide external market context relevant to cash flow dynamics. Refer to:
- Malaysia's Q4 2023 labour market: unemployment rate ({{market.unemploymentRate}}%).
- Wage growth in services sector: {{market.servicesWageGrowth}}%.
- Explain how these factors underscore the importance of an emergency fund and diversified income strategy for the client.
`,
    strategicRecommendationsPrompt: `Generate 3 strategic recommendations for the client, categorized as "Immediate Action", "Mid-Term Strategy", and "Long-Term Consideration", to optimize cash flow. Be specific with suggested actions and potential amounts (e.g., "Propose setting up an automated transfer of RM 400...", "Review and categorize CNY expenses...").`,
    behavioralInsightsPrompt: `Identify and describe a key behavioral insight regarding the client's cash flow management. Focus on patterns like increased discretionary spending when cash flow is high (e.g., 'treat yourself' pattern post-income events).`,
    comparisonBenchmarkingPrompt: `Benchmark the client's income diversification (e.g., {{client.incomeSources}} sources) against their age group. Explain how this diversification contributes to their overall income volatility index compared to peers.`,
  },
  spending: {
    comprehensiveAnalysisPrompt: `Generate a comprehensive analysis of the client's total spending this month. Include:
- Total spending: {{client.totalSpending}} and its percentage of income: {{client.spendingPercentageOfIncome}}%.
- MoM increase from previous month: {{client.spendingChange}}%.
- Top expenditure categories and their amounts: {{client.topSpendingCategories}}.
- Flag any significant anomalies (e.g., acceleration in dining out mid-month/weekends, budget overrun of {{client.budgetOverrun}}).
- Identify 'lifestyle creep' where comfort spending is increasing disproportionately.
`,
    externalContextPrompt: `Provide external market context relevant to spending patterns. Refer to:
- Rising inflation: {{market.petrolInflation}}% increase in RON95 petrol, {{market.restaurantInflation}}% rise in restaurant costs.
- Explain how these contribute to higher transport/dining expenses for Malaysian households.
- Compare client's discretionary spending velocity to market trends.
`,
    strategicRecommendationsPrompt: `Generate 3 strategic recommendations for the client, categorized as "Immediate Action", "Mid-Term Strategy", and "Long-Term Consideration", to improve spending efficiency. Provide concrete, actionable steps (e.g., "Implement a strict weekly spending limit for Food & Dining...", "Encourage meal planning to save RM 250 monthly...", "Review recurring subscription services for RM 127 in potential non-essentials...").`,
    behavioralInsightsPrompt: `Identify and describe a key behavioral insight regarding the client's spending. Focus on correlations like increased discretionary spending during periods of high work-related stress, suggesting spending as a coping mechanism. Emphasize this as a key discussion point.`,
    comparisonBenchmarkingPrompt: `Benchmark the client's discretionary spending as a percentage of income against similar income-level peers who are actively saving for a house down payment. State the percentage difference (e.g., 10% higher).`,
  },
  debt: {
    comprehensiveAnalysisPrompt: `Generate a comprehensive analysis of the client's debt management. Include:
- Total debt reduction this month: {{client.debtReduction}} (e.g., RM 2,450), noting primary drivers (e.g., accelerated CIMB credit card payments).
- Improved Debt-to-Income (DTI) ratio: {{client.dtiRatio}}%, comparing to recommended thresholds (e.g., 30%).
- Current Credit Card Utilization (CCU): {{client.ccu}}% and its potential negative impact despite consistent payments.
`,
    externalContextPrompt: `Provide external market context relevant to debt management. Refer to:
- Bank Negara's recent OPR increase: {{market.oprIncrease}} basis points to {{market.oprRate}}%.
- Explain how this will impact the client's variable-rate housing loan (e.g., starting next month, potentially increasing monthly payments).
- Emphasize the need to review debt strategy to mitigate increased interest costs.
`,
    strategicRecommendationsPrompt: `Generate 3 strategic recommendations for the client, categorized as "Immediate Action", "Mid-Term Strategy", and "Long-Term Consideration", to optimize debt management. Focus on reducing CCU below 30% (e.g., allocate RM 1,200), refinancing options for variable-rate housing loans (e.g., if rates offer 0.5% reduction), and continuing a 'debt avalanche' strategy for highest fixed interest rate loans (e.g., Maybank personal loan).`,
    behavioralInsightsPrompt: `Identify and describe a key behavioral insight regarding the client's debt management. Focus on how motivation is driven by tangible debt reduction progress and the challenge in consistent credit card management to avoid high utilization.`,
    comparisonBenchmarkingPrompt: `Benchmark the client's debt reduction rate (e.g., {{client.debtReductionRate}}% faster) against the average for individuals with similar DTI ratios, showcasing their strong financial discipline.`,
  },
  investments: {
    comprehensiveAnalysisPrompt: `Generate a comprehensive analysis of the client's savings and investment portfolio performance. Include:
- Savings rate this month: {{client.savingsRate}}%, progress towards emergency fund goal.
- Investment portfolio gain: {{client.portfolioReturn}}% this month, outperforming FBM KLCI by {{client.fbmKlciOutperformance}}%.
- Identify key risk: {{client.techConcentration}}% concentration in technology stocks, explaining undue sectoral risk during downturns.
- Emphasize the crucial need for rebalancing for long-term stability.
`,
    externalContextPrompt: `Provide external market context relevant to investment performance. Refer to:
- Global market volatility: US inflation concerns, China's economic reopening, creating mixed signals for ASEAN markets.
- Resilience of Malaysian REITs vs. higher volatility in technology stocks.
- Explain how this reinforces the need for strategic diversification away from concentrated positions.
`,
    strategicRecommendationsPrompt: `Generate 3 strategic recommendations for the client, categorized as "Immediate Action", "Mid-Term Strategy", and "Long-Term Consideration", to optimize savings and investments. Include proposing portfolio rebalancing (reduce tech to <35%, reallocate to healthcare/consumer staples), recommending increased monthly contributions (e.g., RM 300) to robo-advisors (e.g., Versa) for diversification, and conducting an in-depth review of ASB investment potential for low-risk returns.`,
    behavioralInsightsPrompt: `Identify and describe a key behavioral insight regarding the client's investment approach. Focus on a natural inclination towards high-growth sectors driven by perceived higher returns and emphasize the importance of education on risk-adjusted returns and diversification benefits.`,
    comparisonBenchmarkingPrompt: `Benchmark the client's portfolio return (e.g., {{client.portfolioReturnMoM}}% MoM) against the top quartile for balanced portfolios within their risk profile. Note their tech concentration (e.g., {{client.techConcentrationComparedToBenchmark}}% higher) compared to recommended benchmarks.`,
  },
  retirement: {
    comprehensiveAnalysisPrompt: `Generate a comprehensive assessment of the client's retirement planning. Include:
- Readiness score: {{client.readinessScore}}% on track for desired retirement lifestyle at age 60.
- EPF Account 1 balance growth this month: {{client.epfGrowth}} (including employer contributions and dividends).
- Client's self-reported retirement confidence level: {{client.confidenceLevel}}%.
- Note that slight adjustments can significantly enhance long-term security.
`,
    externalContextPrompt: `Provide external market context relevant to retirement planning. Refer to:
- EPF's 2023 dividend: {{market.epfDividend}}% for conventional savings (exceeded expectations).
- Government's continued offering of additional PRS tax relief: up to RM {{market.prsTaxRelief}} (significant, underutilized opportunity for tax optimization and accelerated savings).
`,
    strategicRecommendationsPrompt: `Generate 3 strategic recommendations for the client, categorized as "Immediate Action", "Mid-Term Strategy", and "Long-Term Consideration", to enhance retirement planning. Include advising increased voluntary EPF contributions (e.g., RM 200/month for tax benefits), recommending opening/contributing to a PRS account (utilize full RM 3,000 tax relief), and simulating 'what-if' scenarios (e.g., working until 62 vs. 60) to illustrate impact on projected income and security.`,
    behavioralInsightsPrompt: `Identify and describe a key behavioral insight regarding the client's retirement planning. Focus on their understanding of its importance but potential underestimation of early, consistent, and optimized contributions. Emphasize that visualizing long-term compound growth is effective.`,
    comparisonBenchmarkingPrompt: `Benchmark the client's EPF balance growth rate against the average. Note their overall retirement readiness score (e.g., {{client.readinessScore}}%) is {{client.readinessScoreComparedToPeers}}% below individuals actively utilizing all available tax-advantaged retirement vehicles.`,
  },
  tax: {
    comprehensiveAnalysisPrompt: `Generate a comprehensive analysis of the client's tax efficiency. Include:
- Tax reliefs utilized for 2023: {{client.reliefsUsed}} (primarily lifestyle: RM {{client.lifestyleReliefUsed}} of max RM {{client.lifestyleReliefMax}}, and medical: RM {{client.medicalReliefUsed}}).
- Identified potential unused lifestyle relief: RM {{client.unusedLifestyleRelief}}.
- Complete underutilization of PRS contribution relief: up to RM {{client.prsReliefMax}}.
- Highlight significant opportunity to reduce tax liability for upcoming filing.
`,
    externalContextPrompt: `Provide external market context relevant to tax optimization. Refer to:
- Budget 2024 introductions: enhanced tax relief for EV purchases, increased medical expense limits (to RM {{market.newMedicalLimit}}).
- Approaching e-filing deadline: {{market.efilingDeadline}} (e.g., April 30, 2024), noting penalties for late submission.
- Emphasize staying updated on changes for maximizing benefits.
`,
    strategicRecommendationsPrompt: `Generate 3 strategic recommendations for the client, categorized as "Immediate Action", "Mid-Term Strategy", and "Long-Term Consideration", to optimize tax strategy. Include alerting client to categorize unclassified medical transactions (e.g., RM 450) for additional relief, discussing strategic purchases (e.g., books, sports equipment) to utilize remaining lifestyle relief (e.g., RM 800), and developing a proactive PRS contribution strategy (aim to fully utilize RM 3,000 deduction annually).`,
    behavioralInsightsPrompt: `Identify and describe a key behavioral insight regarding the client's tax management. Focus on good record-keeping but potential lack of full awareness of available tax reliefs or strategic timing of certain expenditures.`,
    comparisonBenchmarkingPrompt: `Benchmark the client's tax relief utilization (e.g., {{client.reliefUtilizationComparison}}% below average) for similar income brackets due to underutilization of investment-related and lifestyle reliefs.`,
  },
  insurance: {
    comprehensiveAnalysisPrompt: `Generate a comprehensive audit of the client's insurance and risk protection. Include:
- Coverage: {{client.coveredAreas}} out of 5 key protection areas (Life, Medical, Accident, Property).
- Adequate life coverage: {{client.lifeCoverageMultiple}}x annual income (aligns with industry best practices).
- Identified critical illness coverage gap, noting its pertinence given client's family history of {{client.familyMedicalHistory}}.
`,
    externalContextPrompt: `Provide external market context relevant to insurance and risk protection. Refer to:
- Rising healthcare costs in Malaysia: averaging {{market.healthcareInflation}}% annually, increased medical inflation post-pandemic.
- Explain why regular review of medical insurance limits is critical.
- Discuss the government's MySalam program for additional coverage, noting if client's income bracket may not qualify for maximum benefits, emphasizing private policy importance.
`,
    strategicRecommendationsPrompt: `Generate 3 strategic recommendations for the client, categorized as "Immediate Action", "Mid-Term Strategy", and "Long-Term Consideration", to optimize insurance coverage. Include proposing a critical illness rider/standalone plan (e.g., additional RM 100,000 coverage), reviewing medical insurance annual limit (e.g., current RM 150,000) against healthcare cost trends (consider increase to RM 200,000), and evaluating home insurance coverage after recent property valuation increase (ensure adequate rebuilding cost coverage).`,
    behavioralInsightsPrompt: `Identify and describe a key behavioral insight regarding the client's receptiveness to risk mitigation. Focus on the need for data-driven insights to justify additional premium outlays and the effectiveness of highlighting family history impact.`,
    comparisonBenchmarkingPrompt: `Benchmark the client's overall protection score (e.g., {{client.protectionScoreComparison}}% higher than basic-only peers) vs. those with comprehensive critical illness coverage.`,
  },
};
// --- End of Initial Prompt Templates ---

const PromptConfigPage: React.FC = () => {
  const [prompts, setPrompts] = useState<ModulePromptTemplates>(
    initialModulePromptTemplates
  );

  const handleChange = (
    moduleId: string,
    promptKey: keyof ModulePromptTemplates[string],
    value: string
  ) => {
    setPrompts((prevPrompts) => ({
      ...prevPrompts,
      [moduleId]: {
        ...prevPrompts[moduleId],
        [promptKey]: value,
      },
    }));
  };

  const handleSave = (moduleId: string) => {
    console.log(`Saving prompts for ${moduleId}:`, prompts[moduleId]);
    // In a real application, you would send this data to your backend API
    alert(`Prompts for "${moduleId}" saved to console!`);
  };

  const handleReset = (moduleId: string) => {
    const confirmReset = window.confirm(
      `Are you sure you want to reset prompts for "${moduleId}" to default?`
    );
    if (confirmReset) {
      setPrompts((prevPrompts) => ({
        ...prevPrompts,
        [moduleId]: initialModulePromptTemplates[moduleId],
      }));
      console.log(`Reset prompts for ${moduleId} to default.`);
      alert(`Prompts for "${moduleId}" reset to default.`);
    }
  };

  // Helper function to extract all unique placeholders for guidance
  const extractPlaceholders = (templates: ModulePromptTemplates) => {
    const placeholders = new Set<string>();
    Object.values(templates).forEach((module) => {
      Object.values(module).forEach((promptText) => {
        const matches = promptText.matchAll(/\{\{([a-zA-Z0-9_.]+)\}\}/g);
        for (const match of matches) {
          if (match[1]) placeholders.add(match[1]);
        }
      });
    });
    return Array.from(placeholders).sort();
  };

  const allPlaceholders = extractPlaceholders(initialModulePromptTemplates);

  return (
    <div className="container mx-auto p-6 space-y-10">
      <h1 className="text-4xl font-bold text-gray-900 mb-6 flex items-center">
        <Settings className="h-9 w-9 mr-4 text-blue-600" />
        AI Insight Prompt Configuration
      </h1>
      <p className="text-lg text-gray-700 mb-8 max-w-2xl">
        Fine-tune the prompts that generate client insights. Use{" "}
        <code>{"{{variable.name}}"}</code> syntax to dynamically inject client
        or market data into the insights.
      </p>

      <Alert className="border-l-4 border-yellow-500 bg-yellow-50">
        <Info className="h-4 w-4 text-yellow-600" />
        <AlertTitle className="text-yellow-800">
          Understanding Placeholders
        </AlertTitle>
        <AlertDescription className="text-sm text-yellow-700">
          <p className="mb-2">
            Values wrapped in double curly braces, such as{" "}
            <code>{"{{client.netCashFlow}}"}</code>, are placeholders. These
            placeholders will be replaced with real client data or external
            market data before the prompt is sent to the AI. You can use them to
            provide the AI with specific, dynamic information to guide its
            analysis.
          </p>

          <p className="font-semibold text-yellow-900">
            Available placeholders across all modules:
            <br />
            <span className="font-normal text-xs text-yellow-700 bg-yellow-100 p-1 rounded-md inline-block max-w-full overflow-x-auto whitespace-nowrap scrollbar-hide">
              {allPlaceholders.join(", ")}
            </span>
          </p>
        </AlertDescription>
      </Alert>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {moduleInsights.map((insight) => {
          const ModuleIcon = insight.icon;
          const currentModulePrompts = prompts[insight.id] || {};

          return (
            <Card
              key={insight.id}
              className="shadow-lg hover:shadow-xl transition-shadow border-t-4 border-blue-500"
            >
              <CardHeader className="pb-4">
                <CardTitle className="flex items-center space-x-3 text-2xl text-blue-700">
                  <ModuleIcon className="h-7 w-7 text-blue-600" />
                  <span>{insight.title} Prompts</span>
                </CardTitle>
                <p className="text-sm text-gray-600 mt-1">
                  Configure the AI prompts for {insight.title}.
                </p>
              </CardHeader>
              <CardContent className="space-y-6">
                <Tabs defaultValue="default" className="space-y-4">
                  <TabsList>
                    <TabsTrigger value="default">Default</TabsTrigger>
                    <TabsTrigger value="custom">Custom</TabsTrigger>
                  </TabsList>

                  <TabsContent value="default" className="space-y-4">
                    <div className="grid gap-8">
                      <Card
                        key={insight.id}
                        className="shadow-lg hover:shadow-xl transition-shadow border-t-4 border-blue-500"
                      >
                        <CardContent className="space-y-6">
                          <div className="space-y-6">
                            {/* Comprehensive Analysis */}
                            <div className="space-y-2">
                              <Label
                                htmlFor={`${insight.id}-comprehensiveAnalysis`}
                                className="text-base font-semibold text-blue-800 flex items-center"
                              >
                                <FlaskConical className="h-4 w-4 mr-2" />
                                Comprehensive Analysis Prompt
                              </Label>
                              <Textarea
                                id={`${insight.id}-comprehensiveAnalysis`}
                                value={
                                  currentModulePrompts.comprehensiveAnalysisPrompt ||
                                  ""
                                }
                                onChange={(e) =>
                                  handleChange(
                                    insight.id,
                                    "comprehensiveAnalysisPrompt",
                                    e.target.value
                                  )
                                }
                                rows={8}
                                className="min-h-[120px] bg-blue-50 border-blue-200 focus-visible:ring-blue-500"
                                placeholder="e.g., 'Analyze the client's cash flow for {{client.month}}. Key data: {{client.netCashFlow}}...'"
                              />
                            </div>

                            {/* External Market Context */}
                            <div className="space-y-2">
                              <Label
                                htmlFor={`${insight.id}-externalContext`}
                                className="text-base font-semibold text-purple-800 flex items-center"
                              >
                                <ExternalLink className="h-4 w-4 mr-2" />
                                External Market Context Prompt
                              </Label>
                              <Textarea
                                id={`${insight.id}-externalContext`}
                                value={
                                  currentModulePrompts.externalContextPrompt ||
                                  ""
                                }
                                onChange={(e) =>
                                  handleChange(
                                    insight.id,
                                    "externalContextPrompt",
                                    e.target.value
                                  )
                                }
                                rows={6}
                                className="min-h-[100px] bg-purple-50 border-purple-200 focus-visible:ring-purple-500"
                                placeholder="e.g., 'Given Malaysia's labour market (unemployment at {{market.unemploymentRate}}%)...'"
                              />
                            </div>

                            {/* Strategic Recommendations */}
                            <div className="space-y-2">
                              <Label
                                htmlFor={`${insight.id}-strategicRecommendations`}
                                className="text-base font-semibold text-green-800 flex items-center"
                              >
                                <Target className="h-4 w-4 mr-2" />
                                Strategic Recommendations Prompt
                              </Label>
                              <Textarea
                                id={`${insight.id}-strategicRecommendations`}
                                value={
                                  currentModulePrompts.strategicRecommendationsPrompt ||
                                  ""
                                }
                                onChange={(e) =>
                                  handleChange(
                                    insight.id,
                                    "strategicRecommendationsPrompt",
                                    e.target.value
                                  )
                                }
                                rows={6}
                                className="min-h-[100px] bg-green-50 border-green-200 focus-visible:ring-green-500"
                                placeholder="e.g., 'Generate 3 strategic recommendations, categorized as Immediate, Mid-Term, Long-Term...'"
                              />
                            </div>

                            {/* Behavioral Insights */}
                            <div className="space-y-2">
                              <Label
                                htmlFor={`${insight.id}-behavioralInsights`}
                                className="text-base font-semibold text-orange-800 flex items-center"
                              >
                                <Lightbulb className="h-4 w-4 mr-2" />
                                Behavioral Insights Prompt
                              </Label>
                              <Textarea
                                id={`${insight.id}-behavioralInsights`}
                                value={
                                  currentModulePrompts.behavioralInsightsPrompt ||
                                  ""
                                }
                                onChange={(e) =>
                                  handleChange(
                                    insight.id,
                                    "behavioralInsightsPrompt",
                                    e.target.value
                                  )
                                }
                                rows={4}
                                className="min-h-[80px] bg-orange-50 border-orange-200 focus-visible:ring-orange-500"
                                placeholder="e.g., 'Based on client spending patterns, describe a behavioral insight like ‘treat yourself’...'"
                              />
                            </div>

                            {/* Comparative Benchmarking */}
                            <div className="space-y-2">
                              <Label
                                htmlFor={`${insight.id}-comparisonBenchmarking`}
                                className="text-base font-semibold text-teal-800 flex items-center"
                              >
                                <Scale className="h-4 w-4 mr-2" />
                                Comparative Benchmarking Prompt
                              </Label>
                              <Textarea
                                id={`${insight.id}-comparisonBenchmarking`}
                                value={
                                  currentModulePrompts.comparisonBenchmarkingPrompt ||
                                  ""
                                }
                                onChange={(e) =>
                                  handleChange(
                                    insight.id,
                                    "comparisonBenchmarkingPrompt",
                                    e.target.value
                                  )
                                }
                                rows={4}
                                className="min-h-[80px] bg-teal-50 border-teal-200 focus-visible:ring-teal-500"
                                placeholder="e.g., 'Benchmark the client's income diversification ({{client.incomeSources}} sources) against their age group...'"
                              />
                            </div>
                          </div>
                        </CardContent>
                      </Card>
                    </div>
                  </TabsContent>
                  <TabsContent value="custom" className="space-y-4">
                    <div className="grid gap-8">
                      <Card
                        key={insight.id}
                        className="shadow-lg hover:shadow-xl transition-shadow border-t-4 border-blue-500"
                      >
                        <CardContent className="space-y-6">
                          <div className="space-y-6">
                            {/* Comprehensive Analysis */}
                            <div className="space-y-2">
                              <Label
                                htmlFor={`${insight.id}-comprehensiveAnalysis`}
                                className="text-base font-semibold text-blue-800 flex justify-between items-center mb-2"
                              >
                                <div className="flex items-center">
                                  <FlaskConical className="h-4 w-4 mr-2" />
                                  Comprehensive Analysis Prompt
                                </div>

                                <Button
                                  variant="ghost"
                                  className="text-red-600 border-red-300 hover:bg-red-50"
                                  onClick={() => handleReset(insight.id)}
                                >
                                  <RotateCcw className="h-4 w-4 mr-2" /> Reset
                                  to Default
                                </Button>
                              </Label>
                              <Textarea
                                id={`${insight.id}-comprehensiveAnalysis`}
                                value={
                                  currentModulePrompts.comprehensiveAnalysisPrompt ||
                                  ""
                                }
                                onChange={(e) =>
                                  handleChange(
                                    insight.id,
                                    "comprehensiveAnalysisPrompt",
                                    e.target.value
                                  )
                                }
                                rows={8}
                                className="min-h-[120px] bg-blue-50 border-blue-200 focus-visible:ring-blue-500"
                                placeholder="e.g., 'Analyze the client's cash flow for {{client.month}}. Key data: {{client.netCashFlow}}...'"
                              />
                            </div>

                            {/* External Market Context */}
                            <div className="space-y-2">
                              <Label
                                htmlFor={`${insight.id}-externalContext`}
                                className="text-base font-semibold text-purple-800 flex justify-between items-center mb-2"
                              >
                                <div className="flex items-center">
                                  <ExternalLink className="h-4 w-4 mr-2" />
                                  External Market Context Prompt
                                </div>

                                <Button
                                  variant="ghost"
                                  className="text-red-600 border-red-300 hover:bg-red-50"
                                  onClick={() => handleReset(insight.id)}
                                >
                                  <RotateCcw className="h-4 w-4 mr-2" /> Reset
                                  to Default
                                </Button>
                              </Label>
                              <Textarea
                                id={`${insight.id}-externalContext`}
                                value={
                                  currentModulePrompts.externalContextPrompt ||
                                  ""
                                }
                                onChange={(e) =>
                                  handleChange(
                                    insight.id,
                                    "externalContextPrompt",
                                    e.target.value
                                  )
                                }
                                rows={6}
                                className="min-h-[100px] bg-purple-50 border-purple-200 focus-visible:ring-purple-500"
                                placeholder="e.g., 'Given Malaysia's labour market (unemployment at {{market.unemploymentRate}}%)...'"
                              />
                            </div>

                            {/* Strategic Recommendations */}
                            <div className="space-y-2">
                              <Label
                                htmlFor={`${insight.id}-strategicRecommendations`}
                                className="text-base font-semibold text-green-800 flex justify-between items-center mb-2"
                              >
                                <div className="flex items-center">
                                  <Target className="h-4 w-4 mr-2" />
                                  Strategic Recommendations Prompt
                                </div>

                                <Button
                                  variant="ghost"
                                  className="text-red-600 border-red-300 hover:bg-red-50"
                                  onClick={() => handleReset(insight.id)}
                                >
                                  <RotateCcw className="h-4 w-4 mr-2" /> Reset
                                  to Default
                                </Button>
                              </Label>
                              <Textarea
                                id={`${insight.id}-strategicRecommendations`}
                                value={
                                  currentModulePrompts.strategicRecommendationsPrompt ||
                                  ""
                                }
                                onChange={(e) =>
                                  handleChange(
                                    insight.id,
                                    "strategicRecommendationsPrompt",
                                    e.target.value
                                  )
                                }
                                rows={6}
                                className="min-h-[100px] bg-green-50 border-green-200 focus-visible:ring-green-500"
                                placeholder="e.g., 'Generate 3 strategic recommendations, categorized as Immediate, Mid-Term, Long-Term...'"
                              />
                            </div>

                            {/* Behavioral Insights */}
                            <div className="space-y-2">
                              <Label
                                htmlFor={`${insight.id}-behavioralInsights`}
                                className="text-base font-semibold text-orange-800 flex justify-between items-center mb-2"
                              >
                                <div className="flex items-center">
                                  <Lightbulb className="h-4 w-4 mr-2" />
                                  Behavioral Insights Prompt
                                </div>

                                <Button
                                  variant="ghost"
                                  className="text-red-600 border-red-300 hover:bg-red-50"
                                  onClick={() => handleReset(insight.id)}
                                >
                                  <RotateCcw className="h-4 w-4 mr-2" /> Reset
                                  to Default
                                </Button>
                              </Label>
                              <Textarea
                                id={`${insight.id}-behavioralInsights`}
                                value={
                                  currentModulePrompts.behavioralInsightsPrompt ||
                                  ""
                                }
                                onChange={(e) =>
                                  handleChange(
                                    insight.id,
                                    "behavioralInsightsPrompt",
                                    e.target.value
                                  )
                                }
                                rows={4}
                                className="min-h-[80px] bg-orange-50 border-orange-200 focus-visible:ring-orange-500"
                                placeholder="e.g., 'Based on spending patterns, describe a behavioral insight like 'treat yourself'...'"
                              />
                            </div>

                            {/* Comparative Benchmarking */}
                            <div className="space-y-2">
                              <Label
                                htmlFor={`${insight.id}-comparisonBenchmarking`}
                                className="text-base font-semibold text-teal-800 flex justify-between items-center mb-2"
                              >
                                <div className="flex items-center">
                                  <Scale className="h-4 w-4 mr-2" />
                                  Comparative Benchmarking Prompt
                                </div>

                                <Button
                                  variant="ghost"
                                  className="text-red-600 border-red-300 hover:bg-red-50"
                                  onClick={() => handleReset(insight.id)}
                                >
                                  <RotateCcw className="h-4 w-4 mr-2" /> Reset
                                  to Default
                                </Button>
                              </Label>
                              <Textarea
                                id={`${insight.id}-comparisonBenchmarking`}
                                value={
                                  currentModulePrompts.comparisonBenchmarkingPrompt ||
                                  ""
                                }
                                onChange={(e) =>
                                  handleChange(
                                    insight.id,
                                    "comparisonBenchmarkingPrompt",
                                    e.target.value
                                  )
                                }
                                rows={4}
                                className="min-h-[80px] bg-teal-50 border-teal-200 focus-visible:ring-teal-500"
                                placeholder="e.g., 'Benchmark the client's income diversification ({{client.incomeSources}} sources)...'"
                              />
                            </div>
                          </div>

                          <div className="flex justify-end gap-3">
                            <Button
                              className="bg-blue-600 hover:bg-blue-700 text-white"
                              onClick={() => handleSave(insight.id)}
                            >
                              <Save className="h-4 w-4 mr-2" /> Save Prompt
                            </Button>
                          </div>
                        </CardContent>
                      </Card>
                    </div>
                  </TabsContent>
                </Tabs>
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );
};

export default PromptConfigPage;
